services:
  file_service:
    build:
      context: .
    env_file:
      - ./config.env
    ports:
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - default_network
  postgres:
    container_name: postgres
    image: postgres:17.2-alpine
    env_file:
      - ./config.env
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql@latest/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "root", "-d", "yandex" ]
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 10s
      start_interval: 5s
    networks:
      - default_network
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    env_file:
      - ./config.env
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://minio:9000/minio/health/live" ]
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 10s
      start_interval: 5s
    networks:
      - default_network
volumes:
  minio_data:
  postgres_data:

networks:
  default_network: