// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file/file.proto

package file

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UploadFileRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Public               bool     `protobuf:"varint,2,opt,name=public,proto3" json:"public,omitempty"`
	RecipientId          string   `protobuf:"bytes,4,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadFileRequest) Reset()         { *m = UploadFileRequest{} }
func (m *UploadFileRequest) String() string { return proto.CompactTextString(m) }
func (*UploadFileRequest) ProtoMessage()    {}
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{0}
}

func (m *UploadFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadFileRequest.Unmarshal(m, b)
}
func (m *UploadFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadFileRequest.Marshal(b, m, deterministic)
}
func (m *UploadFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadFileRequest.Merge(m, src)
}
func (m *UploadFileRequest) XXX_Size() int {
	return xxx_messageInfo_UploadFileRequest.Size(m)
}
func (m *UploadFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadFileRequest proto.InternalMessageInfo

func (m *UploadFileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UploadFileRequest) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

func (m *UploadFileRequest) GetRecipientId() string {
	if m != nil {
		return m.RecipientId
	}
	return ""
}

func (m *UploadFileRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadFileResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadFileResponse) Reset()         { *m = UploadFileResponse{} }
func (m *UploadFileResponse) String() string { return proto.CompactTextString(m) }
func (*UploadFileResponse) ProtoMessage()    {}
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{1}
}

func (m *UploadFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadFileResponse.Unmarshal(m, b)
}
func (m *UploadFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadFileResponse.Marshal(b, m, deterministic)
}
func (m *UploadFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadFileResponse.Merge(m, src)
}
func (m *UploadFileResponse) XXX_Size() int {
	return xxx_messageInfo_UploadFileResponse.Size(m)
}
func (m *UploadFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadFileResponse proto.InternalMessageInfo

func (m *UploadFileResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetFileRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileRequest) Reset()         { *m = GetFileRequest{} }
func (m *GetFileRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileRequest) ProtoMessage()    {}
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{2}
}

func (m *GetFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileRequest.Unmarshal(m, b)
}
func (m *GetFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileRequest.Marshal(b, m, deterministic)
}
func (m *GetFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileRequest.Merge(m, src)
}
func (m *GetFileRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileRequest.Size(m)
}
func (m *GetFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileRequest proto.InternalMessageInfo

func (m *GetFileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetFileResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ContentType          string   `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileResponse) Reset()         { *m = GetFileResponse{} }
func (m *GetFileResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileResponse) ProtoMessage()    {}
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{3}
}

func (m *GetFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileResponse.Unmarshal(m, b)
}
func (m *GetFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileResponse.Marshal(b, m, deterministic)
}
func (m *GetFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileResponse.Merge(m, src)
}
func (m *GetFileResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileResponse.Size(m)
}
func (m *GetFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileResponse proto.InternalMessageInfo

func (m *GetFileResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetFileResponse) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *GetFileResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetFileResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteFileRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileRequest) Reset()         { *m = DeleteFileRequest{} }
func (m *DeleteFileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFileRequest) ProtoMessage()    {}
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{4}
}

func (m *DeleteFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileRequest.Unmarshal(m, b)
}
func (m *DeleteFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileRequest.Merge(m, src)
}
func (m *DeleteFileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFileRequest.Size(m)
}
func (m *DeleteFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileRequest proto.InternalMessageInfo

func (m *DeleteFileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteFileResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileResponse) Reset()         { *m = DeleteFileResponse{} }
func (m *DeleteFileResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFileResponse) ProtoMessage()    {}
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{5}
}

func (m *DeleteFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileResponse.Unmarshal(m, b)
}
func (m *DeleteFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileResponse.Merge(m, src)
}
func (m *DeleteFileResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFileResponse.Size(m)
}
func (m *DeleteFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileResponse proto.InternalMessageInfo

func (m *DeleteFileResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*UploadFileRequest)(nil), "file.UploadFileRequest")
	proto.RegisterType((*UploadFileResponse)(nil), "file.UploadFileResponse")
	proto.RegisterType((*GetFileRequest)(nil), "file.GetFileRequest")
	proto.RegisterType((*GetFileResponse)(nil), "file.GetFileResponse")
	proto.RegisterType((*DeleteFileRequest)(nil), "file.DeleteFileRequest")
	proto.RegisterType((*DeleteFileResponse)(nil), "file.DeleteFileResponse")
}

func init() { proto.RegisterFile("file/file.proto", fileDescriptor_ad806f8986a0c3f6) }

var fileDescriptor_ad806f8986a0c3f6 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0x53, 0xe8, 0xcb, 0x9f, 0xa1, 0x81, 0x30, 0xe1, 0xd5, 0x0d, 0xa7, 0x82, 0x1e, 0x7a,
	0x82, 0x44, 0x13, 0xaf, 0x24, 0xc6, 0x68, 0xbc, 0xae, 0x7a, 0xf1, 0x62, 0x4a, 0x3b, 0x92, 0x8d,
	0xa5, 0x5d, 0xbb, 0x0b, 0x09, 0x7e, 0x42, 0x3f, 0x96, 0xe9, 0xba, 0x94, 0x4a, 0x8d, 0x97, 0x66,
	0x76, 0xfa, 0xcc, 0x3e, 0xbf, 0x99, 0x1d, 0x18, 0xbc, 0x8a, 0x84, 0xe6, 0xc5, 0x67, 0x26, 0xf3,
	0x4c, 0x67, 0xe8, 0x16, 0xf1, 0x74, 0x0b, 0xc3, 0x27, 0x99, 0x64, 0x61, 0x7c, 0x2b, 0x12, 0xe2,
	0xf4, 0xbe, 0x21, 0xa5, 0x11, 0xc1, 0x4d, 0xc3, 0x35, 0x31, 0xc7, 0x77, 0x82, 0x2e, 0x37, 0x31,
	0x9e, 0x40, 0x4b, 0x6e, 0x96, 0x89, 0x88, 0x58, 0xc3, 0x77, 0x82, 0x0e, 0xb7, 0x27, 0x9c, 0x80,
	0x97, 0x53, 0x24, 0xa4, 0xa0, 0x54, 0xbf, 0x88, 0x98, 0xb9, 0xa6, 0xa6, 0x57, 0xe6, 0xee, 0xe3,
	0xe2, 0xba, 0x38, 0xd4, 0x21, 0xfb, 0xe7, 0x3b, 0x81, 0xc7, 0x4d, 0x3c, 0x3d, 0x07, 0xac, 0xfa,
	0x2a, 0x99, 0xa5, 0x8a, 0xb0, 0x0f, 0x0d, 0x11, 0x5b, 0xdb, 0x86, 0x88, 0xa7, 0x3e, 0xf4, 0xef,
	0x48, 0x57, 0xd1, 0x8e, 0x15, 0x12, 0x06, 0xa5, 0xc2, 0x5e, 0xf2, 0x1b, 0xfd, 0x04, 0xbc, 0x28,
	0x4b, 0x75, 0xc1, 0xa8, 0x77, 0x92, 0x4c, 0x0f, 0x5d, 0xde, 0xb3, 0xb9, 0xc7, 0x9d, 0x34, 0x65,
	0x4a, 0x7c, 0x10, 0x6b, 0xfa, 0x4e, 0xd0, 0xe4, 0x26, 0x2e, 0xc9, 0xdd, 0x0a, 0xf9, 0x19, 0x0c,
	0x6f, 0x28, 0x21, 0x4d, 0x7f, 0x61, 0xcd, 0x00, 0xab, 0x22, 0x4b, 0xc6, 0xa0, 0xad, 0x36, 0x51,
	0x44, 0x4a, 0x19, 0x69, 0x87, 0xef, 0x8f, 0x17, 0x9f, 0x0e, 0x78, 0x85, 0x54, 0x3d, 0x50, 0xbe,
	0x15, 0x11, 0xe1, 0x02, 0xe0, 0x30, 0x1f, 0x3c, 0x9d, 0x99, 0x87, 0xab, 0xbd, 0xd4, 0x98, 0xd5,
	0x7f, 0x58, 0xaf, 0x2b, 0x68, 0xdb, 0xc1, 0xe0, 0xe8, 0x5b, 0xf4, 0x73, 0x92, 0xe3, 0xff, 0x47,
	0x59, 0x5b, 0xb7, 0x00, 0x38, 0x90, 0xef, 0x8d, 0x6b, 0x0d, 0xef, 0x8d, 0xeb, 0x4d, 0x5e, 0x8f,
	0x9e, 0x51, 0xbe, 0xad, 0xe6, 0x6b, 0x52, 0x2a, 0x4c, 0x57, 0x94, 0x9b, 0x9d, 0x5b, 0xb6, 0xcc,
	0xd2, 0x5d, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x4d, 0x58, 0x4b, 0x87, 0x02, 0x00, 0x00,
}
